// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBjLwfyu3VYenRakHgUuwkuDezUITjHVRA',
    appId: '1:698219180098:web:3bb82954099364fab47ddb',
    messagingSenderId: '698219180098',
    projectId: 'e-commerce-app-7257d',
    authDomain: 'e-commerce-app-7257d.firebaseapp.com',
    storageBucket: 'e-commerce-app-7257d.firebasestorage.app',
    measurementId: 'G-XV93KY9CC2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAI3awgNVNe38lITGJ_HuFHyWDRAKb5IFI',
    appId: '1:698219180098:android:74df69517c6bab7bb47ddb',
    messagingSenderId: '698219180098',
    projectId: 'e-commerce-app-7257d',
    storageBucket: 'e-commerce-app-7257d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAIbmr_7eV-yv30UvEQ3UdUKrCHAEFTlUU',
    appId: '1:698219180098:ios:65f2e06168d79c75b47ddb',
    messagingSenderId: '698219180098',
    projectId: 'e-commerce-app-7257d',
    storageBucket: 'e-commerce-app-7257d.firebasestorage.app',
    iosBundleId: 'com.example.eCommerceApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAIbmr_7eV-yv30UvEQ3UdUKrCHAEFTlUU',
    appId: '1:698219180098:ios:65f2e06168d79c75b47ddb',
    messagingSenderId: '698219180098',
    projectId: 'e-commerce-app-7257d',
    storageBucket: 'e-commerce-app-7257d.firebasestorage.app',
    iosBundleId: 'com.example.eCommerceApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBjLwfyu3VYenRakHgUuwkuDezUITjHVRA',
    appId: '1:698219180098:web:03040f141a2ec56bb47ddb',
    messagingSenderId: '698219180098',
    projectId: 'e-commerce-app-7257d',
    authDomain: 'e-commerce-app-7257d.firebaseapp.com',
    storageBucket: 'e-commerce-app-7257d.firebasestorage.app',
    measurementId: 'G-5Q8ZV2G8NW',
  );
}
